export const INITIAL_COLUMNS = [
  { id: 'todo', title: 'To Do', colorIndicator: 'indicator-todo' },
  { id: 'in_progress', title: 'In Progress', colorIndicator: 'indicator-in_progress' },
  { id: 'review', title: 'In Review', colorIndicator: 'indicator-review' },
  { id: 'done', title: 'Completed', colorIndicator: 'indicator-done' },
];

export const INITIAL_TASKS = [
  {
    id: 'task-1',
    title: 'Setup Drag & Drop Kanban Foundation',
    description: 'Implement @hello-pangea/dnd for interactive card dragging between columns.',
    status: 'todo',
    priority: 'high',
    tags: ['Frontend', 'DND'],
    assignee: 'Niro (Lead)',
    dueDate: '2026-08-15',
  },
  {
    id: 'task-2',
    title: 'Build Task Edit Modal & Filter UI',
    description: 'Create responsive modals for editing task details, search bar, and priority filters.',
    status: 'in_progress',
    priority: 'high',
    tags: ['UI/UX', 'Components'],
    assignee: 'Alex Rivers',
    dueDate: '2026-08-16',
  },
  {
    id: 'task-3',
    title: 'Connect REST API Backend Wiring',
    description: 'Integrate client state with Node/Express REST endpoints for real-time synchronization.',
    status: 'in_progress',
    priority: 'medium',
    tags: ['API', 'State'],
    assignee: 'Sarah Chen',
    dueDate: '2026-08-18',
  },
  {
    id: 'task-4',
    title: 'Implement User JWT Authentication',
    description: 'Login, Registration, and protected token session handling.',
    status: 'review',
    priority: 'high',
    tags: ['Auth', 'Security'],
    assignee: 'John Doe',
    dueDate: '2026-08-14',
  },
  {
    id: 'task-5',
    title: 'Design UI Theme & Design Tokens',
    description: 'Configure dark mode colors, fonts (Inter & Outfit), and glassmorphism styling.',
    status: 'done',
    priority: 'low',
    tags: ['Design System'],
    assignee: 'Alex Rivers',
    dueDate: '2026-08-13',
  },
];

export const INITIAL_MEMBERS = [
  {
    id: 'mem-1',
    name: 'Niro (Lead)',
    email: 'niro@collabboard.io',
    studentId: 'IT2200101',
    role: 'Owner',
    designation: 'Team Leader & Full Stack Dev',
    bio: 'Overseeing board architecture, real-time collaboration, and end-to-end integration.',
    skills: ['React', 'Node.js', 'Socket.io', 'MongoDB'],
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    online: true,
  },
  {
    id: 'mem-2',
    name: 'Alex Rivers',
    email: 'alex.rivers@design.io',
    studentId: 'IT2200102',
    role: 'Admin',
    designation: 'UI/UX & Frontend Designer',
    bio: 'Crafting pastel design systems, responsive interfaces, and interaction micro-animations.',
    skills: ['Figma', 'CSS Architecture', 'React UI', 'Accessibility'],
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    online: true,
  },
  {
    id: 'mem-3',
    name: 'Sarah Chen',
    email: 'sarah.chen@tech.dev',
    studentId: 'IT2200103',
    role: 'Member',
    designation: 'Backend & REST API Engineer',
    bio: 'Developing secure endpoints, JWT auth middleware, and MongoDB data aggregation.',
    skills: ['Express.js', 'REST APIs', 'JWT', 'Mongoose'],
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    online: false,
  },
  {
    id: 'mem-4',
    name: 'John Doe',
    email: 'john.doe@company.org',
    studentId: 'IT2200104',
    role: 'Member',
    designation: 'Frontend React Developer',
    bio: 'Building Kanban drag-and-drop mechanics, interactive modals, and client state.',
    skills: ['React DnD', 'JavaScript ES6+', 'State Management'],
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    online: true,
  },
  {
    id: 'mem-5',
    name: 'Dilshan Perera',
    email: 'dilshan.p@collabboard.io',
    studentId: 'IT2200105',
    role: 'Member',
    designation: 'QA & Test Automation Specialist',
    bio: 'Conducting unit testing, cross-browser compatibility tests, and validation flows.',
    skills: ['Vitest', 'Testing Library', 'API Verification'],
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    online: true,
  },
  {
    id: 'mem-6',
    name: 'Kavindu Silva',
    email: 'kavindu.s@tech.dev',
    studentId: 'IT2200106',
    role: 'Member',
    designation: 'Database & Cloud Architect',
    bio: 'Designing database schemas, indexing strategies, and cloud deployment pipelines.',
    skills: ['MongoDB Atlas', 'Docker', 'Performance Tuning'],
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
    online: true,
  },
  {
    id: 'mem-7',
    name: 'Sanduni Fernando',
    email: 'sanduni.f@collabboard.io',
    studentId: 'IT2200107',
    role: 'Admin',
    designation: 'Project Manager & Scrum Master',
    bio: 'Coordinating sprints, backlog prioritization, deliverable tracking, and team meetings.',
    skills: ['Agile / Scrum', 'Sprint Planning', 'Requirement Analysis'],
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    online: false,
  },
];


