export const INITIAL_COLUMNS = [
  { id: 'todo', title: 'To Do', colorIndicator: 'indicator-todo' },
  { id: 'in_progress', title: 'In Progress', colorIndicator: 'indicator-in_progress' },
  { id: 'review', title: 'In Review', colorIndicator: 'indicator-review' },
  { id: 'done', title: 'Completed', colorIndicator: 'indicator-done' },
];

export const INITIAL_TASKS = [
  {
    id: 'task-1',
    title: 'Setup Drag & Drop Kanban Foundation',
    description: 'Implement @hello-pangea/dnd for interactive card dragging between columns.',
    status: 'todo',
    priority: 'high',
    tags: ['Frontend', 'DND'],
    assignee: 'Niro (Lead)',
    dueDate: '2026-08-15',
  },
  {
    id: 'task-2',
    title: 'Build Task Edit Modal & Filter UI',
    description: 'Create responsive modals for editing task details, search bar, and priority filters.',
    status: 'in_progress',
    priority: 'high',
    tags: ['UI/UX', 'Components'],
    assignee: 'Alex Rivers',
    dueDate: '2026-08-16',
  },
  {
    id: 'task-3',
    title: 'Connect REST API Backend Wiring',
    description: 'Integrate client state with Node/Express REST endpoints for real-time synchronization.',
    status: 'in_progress',
    priority: 'medium',
    tags: ['API', 'State'],
    assignee: 'Sarah Chen',
    dueDate: '2026-08-18',
  },
  {
    id: 'task-4',
    title: 'Implement User JWT Authentication',
    description: 'Login, Registration, and protected token session handling.',
    status: 'review',
    priority: 'high',
    tags: ['Auth', 'Security'],
    assignee: 'John Doe',
    dueDate: '2026-08-14',
  },
  {
    id: 'task-5',
    title: 'Design UI Theme & Design Tokens',
    description: 'Configure dark mode colors, fonts (Inter & Outfit), and glassmorphism styling.',
    status: 'done',
    priority: 'low',
    tags: ['Design System'],
    assignee: 'Alex Rivers',
    dueDate: '2026-08-13',
  },
];
